<?php

/**
 * BaseFortune
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $author
 * @property string $title
 * @property string $content
 * @property integer $votes
 * @property Doctrine_Collection $Comments
 * 
 * @method string              getAuthor()   Returns the current record's "author" value
 * @method string              getTitle()    Returns the current record's "title" value
 * @method string              getContent()  Returns the current record's "content" value
 * @method integer             getVotes()    Returns the current record's "votes" value
 * @method Doctrine_Collection getComments() Returns the current record's "Comments" collection
 * @method Fortune             setAuthor()   Sets the current record's "author" value
 * @method Fortune             setTitle()    Sets the current record's "title" value
 * @method Fortune             setContent()  Sets the current record's "content" value
 * @method Fortune             setVotes()    Sets the current record's "votes" value
 * @method Fortune             setComments() Sets the current record's "Comments" collection
 * 
 * @package    sftunes
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFortune extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fortune');
        $this->hasColumn('author', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', 5000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 5000,
             ));
        $this->hasColumn('votes', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));


        $this->index('author_idx', array(
             'fields' => 
             array(
              0 => 'author',
             ),
             ));
        $this->index('votes_idx', array(
             'fields' => 
             array(
              0 => 'votes',
             ),
             ));
        $this->index('author_votes_idx', array(
             'fields' => 
             array(
              0 => 'author',
              1 => 'votes',
             ),
             ));
        $this->index('date_idx', array(
             'fields' => 
             array(
              0 => 'created_at',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Comment as Comments', array(
             'local' => 'id',
             'foreign' => 'fortune_id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}