<?php

/**
 * Fortune
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sftunes
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Fortune extends BaseFortune
{
  public function updateVote($direction)
  {
    $votes = $this->getVotes();
    $votes += 'up' === $direction ? 1 : -1;
    $this->setVotes($votes);
    $this->save();
  }
}
